services:
  web:
    build:
      context: .
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.12-slim}
    ports:
      - "${DEV_LOCAL_PORT:-8082}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - FLASK_DEBUG=${FLASK_DEBUG:-true}
      - FLASK_ENV=development
    command: ["python", "main.py"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./pyproject.toml