#cloud-config

# Create deploy user with sudo access
users:
  - name: deploy
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    lock_passwd: false
    passwd: ${deploy_password_hash}

# Update package list and install essential packages
package_update: true
package_upgrade: true

packages:
  - git
  - docker.io
  - curl
  - jq
  - ufw
  - fail2ban
  - unattended-upgrades
  - python3
  - python3-pip

# Basic system configuration
runcmd:
  # Setup Docker
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker deploy
  
  # Configure firewall (SSH only)
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw --force enable
  
  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Setup automatic security updates
  - echo 'Unattended-Upgrade::Automatic-Reboot "false";' >> /etc/apt/apt.conf.d/50unattended-upgrades
  
  # Create basic directories and fix permissions
  - mkdir -p /home/deploy/app
  - chown -R deploy:deploy /home/deploy
  
  # Signal cloud-init completion
  - touch /home/deploy/.cloud-init-complete
  - chown deploy:deploy /home/deploy/.cloud-init-complete

# Write basic info file
write_files:
  - path: /home/deploy/system-info.txt
    content: |
      System Setup Complete
      ====================
      User: deploy
      Docker: Installed and configured
      Firewall: Enabled (SSH only)
      Security: fail2ban enabled, unattended-upgrades configured
      
      Ready for deployment via Ansible.
    owner: deploy:deploy
    permissions: '0644'

# Final status
final_message: |
  Cloud-init basic setup complete!
  
  System is ready for deployment.
  SSH access: ssh deploy@YOUR_VM_IP