name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            uv run python -m pytest tests/ -v
          else
            echo "No tests directory found - skipping tests"
          fi

      - name: Test Flask app starts
        run: |
          uv run python main.py &
          PID=$!
          sleep 3
          curl -f http://localhost:8080/health || exit 1
          kill $PID

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t test-image .

      - name: Test Docker container
        run: |
          docker run -d -p 8080:8080 -e PORT=8080 --name test-container test-image
          sleep 5
          curl -f http://localhost:8080/health
          docker stop test-container
          docker rm test-container